<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>

		<PackAsTool>true</PackAsTool>
		<ToolCommandName>nitec</ToolCommandName>
		<PackageOutputPath>../../nupkg</PackageOutputPath>
        <LangVersion>preview</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.CommandLine" Version="2.0.0-beta6.25358.103" />
		<ProjectReference Include="..\NiTiS.Compiler.NiteCode\NiTiS.Compiler.NiteCode.csproj" />

		<ProjectReference Include="..\NiTiS.Compiler\NiTiS.Compiler.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="*.nite">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>