<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.0" />
		<PackageReference Include="libLLVM" Version="20.1.2" />
		<PackageReference Include="LLVMSharp" Version="20.1.2" />
		<PackageReference Include="LLVMSharp.Interop" Version="20.1.2" />
	</ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>$(AssemblyName).Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="CodeAnalysis\Declarations\" />
    </ItemGroup>

</Project>
