<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
        <LangVersion>14.0</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.0" />
		<PackageReference Include="LLVMSharp" Version="16.0.0" />
	</ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>$(AssemblyName).Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="CodeAnalysis\Symbols\Metadata\Nlib\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\NiteLang.Metadata\NiteLang.Metadata.csproj" />
    </ItemGroup>

</Project>
