namespace NiteCompiler.CodeAnalysis.Symbols;

public abstract class Symbol
{
	private protected Symbol() {}

	/// <summary>
	/// Returns true if symbol generated by compiled and not accessible from source code directly.
	/// </summary>
	public virtual bool IsSynthetic => false;

	public abstract SymbolKind Kind { get; }
}