using System.Collections.Generic;
using NiteCompiler.CodeAnalysis.Syntax;
using NiteCompiler.CodeAnalysis.Text;

namespace NiteCompiler.CodeAnalysis.Symbols;

public abstract class Symbol
{
	public abstract SymbolKind Kind { get; }
	/// <summary>
	/// Returns <see langword="true" /> if symbol generated by compiled and not accessible from source code directly.
	/// </summary>
	public virtual bool IsSynthetic => false;
	public virtual IEnumerable<SourceSpan> Locations => [];
	public virtual SyntaxTree? SyntaxTree => null;
	public virtual string Name => string.Empty;

	private protected Symbol() {}
}