using System.Collections.Generic;
using System.Collections.Immutable;
using NiteCompiler.CodeAnalysis.Syntax;
using NiteCompiler.CodeAnalysis.Text;
using NiteCompiler.Diagnostics;

namespace NiteCompiler.CodeAnalysis.Symbols;

public abstract class Symbol
{
	public abstract SymbolKind Kind { get; }

	/// <summary>
	/// Returns <see langword="true" /> if symbol generated by compiled and not accessible from source code directly.
	/// </summary>
	public virtual bool IsSynthetic => false;

	public virtual ImmutableArray<Location> Locations => [];
	public virtual string Name => string.Empty;

	private protected Symbol() {}
}