<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>

		<PackAsTool>true</PackAsTool>
		<ToolCommandName>nitec</ToolCommandName>
		<PackageOutputPath>../../nupkg</PackageOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />

		<ProjectReference Include="..\Nlr.Compiler\Nlr.Compiler.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="*.nite">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>