<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.0" />
		<PackageReference Include="Microsoft.Extensions.Primitives" Version="9.0.0-rc.2.24473.5" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Nibc\" />
	</ItemGroup>

</Project>
