<Project>
	<PropertyGroup>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Authors>NiTiSon and contributors</Authors>
		<Description>NiteCode &amp;amp; Nibc compiler</Description>
		<TargetFramework>net9.0</TargetFramework>
        <LangVersion>13.0</LangVersion>

		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsTrimmable>true</IsTrimmable>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<TrimMode>full</TrimMode>
		<IsAotCompatible>true</IsAotCompatible>
		<EnableAotAnalyzer>true</EnableAotAnalyzer>

		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<VersionPrefix>0.1</VersionPrefix>

		<DebugType>portable</DebugType>
		<EmbedAllSources>true</EmbedAllSources>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DotNet.ReproducibleBuilds" Version="1.2.25" PrivateAssets="All"/>
		<PackageReference Include="DotNet.ReproducibleBuilds.Isolated" Version="1.2.25" PrivateAssets="All"/>
	</ItemGroup>
</Project>