namespace NiTiS.Compiler.NiteCode.CodeAnalysis.Syntax;

public static class SyntaxKindFacts
{
	public static string? GetText(SyntaxKind kind)
	{
		return kind switch
		{
			SyntaxKind.PlusToken => "+",
			SyntaxKind.MinusToken => "-",
			SyntaxKind.ExclamationToken => "!",
			SyntaxKind.DoubleQuote => "\"",
			SyntaxKind.HashToken => "#",
			SyntaxKind.DollarToken => "$",
			SyntaxKind.PercentToken => "%",
			SyntaxKind.AmpersandToken => "&",
			SyntaxKind.QuoteToken => "'",
			SyntaxKind.OpenParenToken => "(",
			SyntaxKind.CloseParenToken => ")",
			SyntaxKind.AsteriskToken => "*",
			SyntaxKind.CommaToken => ",",
			SyntaxKind.DotToken => ".",
			SyntaxKind.SlashToken => "/",
			SyntaxKind.ColonToken => ":",
			SyntaxKind.SemicolonToken => ";",
			SyntaxKind.LessThanToken => "<",
			SyntaxKind.EqualsToken => "=",
			SyntaxKind.GreaterThanToken => ">",
			SyntaxKind.QuestionToken => "?",
			SyntaxKind.AtToken => "@",
			SyntaxKind.OpenBracketToken => "[",
			SyntaxKind.BackslashToken => "\\",
			SyntaxKind.CloseBracketToken => "]",
			SyntaxKind.CircumflexToken => "^",
			SyntaxKind.UnderscoreToken => "_",
			SyntaxKind.BacktickToken => "`",
			SyntaxKind.OpenBraceToken => "{",
			SyntaxKind.PipeToken => "|",
			SyntaxKind.CloseBraceToken => "}",
			SyntaxKind.TildeToken => "~",
			SyntaxKind.MinusMinusToken => "--",
			SyntaxKind.PlusPlusToken => "++",
			SyntaxKind.PlusEqualsToken => "+=",
			SyntaxKind.MinusEqualsToken => "-=",
			SyntaxKind.AsteriskEqualsToken => "*=",
			SyntaxKind.SlashEqualsToken => "/=",
			SyntaxKind.PercentEqualsToken => "%=",
			SyntaxKind.AmpersandEqualsToken => "&=",
			SyntaxKind.PipeEqualsToken => "|=",
			SyntaxKind.CircumflexEqualsToken => "^=",
			SyntaxKind.LeftShiftToken => "<<",
			SyntaxKind.RightShiftToken => ">>",
			SyntaxKind.UnsignedRightShiftToken => ">>>",
			SyntaxKind.LeftShiftEqualsToken => "<<=",
			SyntaxKind.RightShiftEqualsToken => ">>=",
			SyntaxKind.UnsignedRightShiftEqualsToken => ">>>=",

			// Keywords
			SyntaxKind.TrueKeyword => "true",
			SyntaxKind.FalseKeyword => "false",
			SyntaxKind.UseKeyword => "use",
			SyntaxKind.IfKeyword => "if",
			SyntaxKind.ElseKeyword => "else",
			SyntaxKind.LoopKeyword => "loop",
			SyntaxKind.ForKeyword => "for",
			SyntaxKind.DoKeyword => "do",
			SyntaxKind.WhileKeyword => "while",
			SyntaxKind.BreakKeyword => "break",
			SyntaxKind.ReturnKeyword => "return",
			SyntaxKind.ContinueKeyword => "continue",
			SyntaxKind.GetKeyword => "get",
			SyntaxKind.SetKeyword => "set",
			SyntaxKind.WhereKeyword => "where",
			SyntaxKind.WhenKeyword => "when",
			SyntaxKind.IsKeyword => "is",
			SyntaxKind.AsKeyword => "as",
			SyntaxKind.OperatorKeyword => "operator",
			SyntaxKind.CommutativeKeyword => "commutative",
			SyntaxKind.PublicKeyword => "public",
			SyntaxKind.FriendKeyword => "friend",
			SyntaxKind.ProtectedKeyword => "protected",
			SyntaxKind.InternalKeyword => "internal",
			SyntaxKind.FamilyKeyword => "family",
			SyntaxKind.PrivateKeyword => "private",

			SyntaxKind.I8Keyword => "i8",
			SyntaxKind.I16Keyword => "i16",
			SyntaxKind.I32Keyword => "i32",
			SyntaxKind.I64Keyword => "i64",
			SyntaxKind.U8Keyword => "u8",
			SyntaxKind.U16Keyword => "u16",
			SyntaxKind.U32Keyword => "u32",
			SyntaxKind.U64Keyword => "u64",
			SyntaxKind.F16Keyword => "f16",
			SyntaxKind.F32Keyword => "f32",
			SyntaxKind.F64Keyword => "f64",
			SyntaxKind.VoidKeyword => "void",
			SyntaxKind.BoolKeyword => "bool",
			SyntaxKind.Invalid => "<invalid/>",
			SyntaxKind.EndOfFile => "<eof/>",
			_ => null
		};
	}
}